//! 固定本阶段 chain spec、libp2p、network、sync 与 transactions 的 61 个来源文件。
//!
//! `include_bytes` 在后续编译测试时要求每个文件存在；逐字节 SHA-256 由
//! 塔塔文档库中的 CitizenSDK 来源记录和导入审计共同记录。

const REQUIRED_FILES: [(&str, &[u8]); 61] = [
    ("src/chain_spec.rs", include_bytes!("../src/chain_spec.rs")),
    (
        "src/chain_spec/light_sync_state.rs",
        include_bytes!("../src/chain_spec/light_sync_state.rs"),
    ),
    (
        "src/chain_spec/structs.rs",
        include_bytes!("../src/chain_spec/structs.rs"),
    ),
    (
        "src/chain_spec/tests.rs",
        include_bytes!("../src/chain_spec/tests.rs"),
    ),
    (
        "src/chain_spec/tests/example.json",
        include_bytes!("../src/chain_spec/tests/example.json"),
    ),
    (
        "src/chain_spec/tests/issue-598.json",
        include_bytes!("../src/chain_spec/tests/issue-598.json"),
    ),
    ("src/informant.rs", include_bytes!("../src/informant.rs")),
    ("src/libp2p.rs", include_bytes!("../src/libp2p.rs")),
    (
        "src/libp2p/collection.rs",
        include_bytes!("../src/libp2p/collection.rs"),
    ),
    (
        "src/libp2p/collection/multi_stream.rs",
        include_bytes!("../src/libp2p/collection/multi_stream.rs"),
    ),
    (
        "src/libp2p/collection/single_stream.rs",
        include_bytes!("../src/libp2p/collection/single_stream.rs"),
    ),
    (
        "src/libp2p/connection.rs",
        include_bytes!("../src/libp2p/connection.rs"),
    ),
    (
        "src/libp2p/connection/established.rs",
        include_bytes!("../src/libp2p/connection/established.rs"),
    ),
    (
        "src/libp2p/connection/established/multi_stream.rs",
        include_bytes!("../src/libp2p/connection/established/multi_stream.rs"),
    ),
    (
        "src/libp2p/connection/established/single_stream.rs",
        include_bytes!("../src/libp2p/connection/established/single_stream.rs"),
    ),
    (
        "src/libp2p/connection/established/substream.rs",
        include_bytes!("../src/libp2p/connection/established/substream.rs"),
    ),
    (
        "src/libp2p/connection/established/tests.rs",
        include_bytes!("../src/libp2p/connection/established/tests.rs"),
    ),
    (
        "src/libp2p/connection/multistream_select.rs",
        include_bytes!("../src/libp2p/connection/multistream_select.rs"),
    ),
    (
        "src/libp2p/connection/noise.rs",
        include_bytes!("../src/libp2p/connection/noise.rs"),
    ),
    (
        "src/libp2p/connection/single_stream_handshake.rs",
        include_bytes!("../src/libp2p/connection/single_stream_handshake.rs"),
    ),
    (
        "src/libp2p/connection/single_stream_handshake/tests.rs",
        include_bytes!("../src/libp2p/connection/single_stream_handshake/tests.rs"),
    ),
    (
        "src/libp2p/connection/webrtc_framing.rs",
        include_bytes!("../src/libp2p/connection/webrtc_framing.rs"),
    ),
    (
        "src/libp2p/connection/yamux.rs",
        include_bytes!("../src/libp2p/connection/yamux.rs"),
    ),
    (
        "src/libp2p/connection/yamux/header.rs",
        include_bytes!("../src/libp2p/connection/yamux/header.rs"),
    ),
    (
        "src/libp2p/connection/yamux/tests.rs",
        include_bytes!("../src/libp2p/connection/yamux/tests.rs"),
    ),
    (
        "src/libp2p/multiaddr.rs",
        include_bytes!("../src/libp2p/multiaddr.rs"),
    ),
    (
        "src/libp2p/multihash.rs",
        include_bytes!("../src/libp2p/multihash.rs"),
    ),
    (
        "src/libp2p/peer_id.rs",
        include_bytes!("../src/libp2p/peer_id.rs"),
    ),
    (
        "src/libp2p/read_write.rs",
        include_bytes!("../src/libp2p/read_write.rs"),
    ),
    (
        "src/libp2p/websocket.rs",
        include_bytes!("../src/libp2p/websocket.rs"),
    ),
    (
        "src/libp2p/with_buffers.rs",
        include_bytes!("../src/libp2p/with_buffers.rs"),
    ),
    ("src/network.rs", include_bytes!("../src/network.rs")),
    (
        "src/network/basic_peering_strategy.rs",
        include_bytes!("../src/network/basic_peering_strategy.rs"),
    ),
    (
        "src/network/codec.rs",
        include_bytes!("../src/network/codec.rs"),
    ),
    (
        "src/network/codec/block_announces.rs",
        include_bytes!("../src/network/codec/block_announces.rs"),
    ),
    (
        "src/network/codec/block_request.rs",
        include_bytes!("../src/network/codec/block_request.rs"),
    ),
    (
        "src/network/codec/grandpa.rs",
        include_bytes!("../src/network/codec/grandpa.rs"),
    ),
    (
        "src/network/codec/grandpa_warp_sync.rs",
        include_bytes!("../src/network/codec/grandpa_warp_sync.rs"),
    ),
    (
        "src/network/codec/identify.rs",
        include_bytes!("../src/network/codec/identify.rs"),
    ),
    (
        "src/network/codec/kademlia.rs",
        include_bytes!("../src/network/codec/kademlia.rs"),
    ),
    (
        "src/network/codec/state_request.rs",
        include_bytes!("../src/network/codec/state_request.rs"),
    ),
    (
        "src/network/codec/storage_call_proof.rs",
        include_bytes!("../src/network/codec/storage_call_proof.rs"),
    ),
    (
        "src/network/kademlia.rs",
        include_bytes!("../src/network/kademlia.rs"),
    ),
    (
        "src/network/kademlia/kbuckets.rs",
        include_bytes!("../src/network/kademlia/kbuckets.rs"),
    ),
    (
        "src/network/service.rs",
        include_bytes!("../src/network/service.rs"),
    ),
    ("src/sync.rs", include_bytes!("../src/sync.rs")),
    ("src/sync/all.rs", include_bytes!("../src/sync/all.rs")),
    (
        "src/sync/all_forks.rs",
        include_bytes!("../src/sync/all_forks.rs"),
    ),
    (
        "src/sync/all_forks/disjoint.rs",
        include_bytes!("../src/sync/all_forks/disjoint.rs"),
    ),
    (
        "src/sync/all_forks/pending_blocks.rs",
        include_bytes!("../src/sync/all_forks/pending_blocks.rs"),
    ),
    (
        "src/sync/all_forks/sources.rs",
        include_bytes!("../src/sync/all_forks/sources.rs"),
    ),
    ("src/sync/para.rs", include_bytes!("../src/sync/para.rs")),
    (
        "src/sync/warp_sync.rs",
        include_bytes!("../src/sync/warp_sync.rs"),
    ),
    (
        "src/transactions.rs",
        include_bytes!("../src/transactions.rs"),
    ),
    (
        "src/transactions/light_pool.rs",
        include_bytes!("../src/transactions/light_pool.rs"),
    ),
    (
        "src/transactions/light_pool/tests.rs",
        include_bytes!("../src/transactions/light_pool/tests.rs"),
    ),
    (
        "src/transactions/pool.rs",
        include_bytes!("../src/transactions/pool.rs"),
    ),
    (
        "src/transactions/pool/tests.rs",
        include_bytes!("../src/transactions/pool/tests.rs"),
    ),
    (
        "src/transactions/validate.rs",
        include_bytes!("../src/transactions/validate.rs"),
    ),
    (
        "src/transactions/validate/test-fixture.json",
        include_bytes!("../src/transactions/validate/test-fixture.json"),
    ),
    (
        "src/transactions/validate/tests.rs",
        include_bytes!("../src/transactions/validate/tests.rs"),
    ),
];

#[test]
fn all_network_sync_and_transaction_sources_are_present_and_non_empty() {
    for (path, content) in REQUIRED_FILES {
        assert!(!content.is_empty(), "网络/同步/交易来源文件为空: {path}");
    }
}
