//! 固定本阶段状态证明、runtime、轻数据库、JSON-RPC 和 SS58 的 64 个来源文件。
//!
//! `include_bytes` 在后续编译测试时要求每个文件存在；逐字节 SHA-256 由
//! 塔塔文档库中的 CitizenSDK 来源记录和导入审计共同记录。

const REQUIRED_FILES: [(&str, &[u8]); 64] = [
    ("src/database.rs", include_bytes!("../src/database.rs")),
    (
        "src/database/finalized_serialize.rs",
        include_bytes!("../src/database/finalized_serialize.rs"),
    ),
    (
        "src/database/finalized_serialize/defs.rs",
        include_bytes!("../src/database/finalized_serialize/defs.rs"),
    ),
    (
        "src/database/full_sqlite.rs",
        include_bytes!("../src/database/full_sqlite.rs"),
    ),
    (
        "src/database/full_sqlite/open.rs",
        include_bytes!("../src/database/full_sqlite/open.rs"),
    ),
    (
        "src/database/full_sqlite/tests.rs",
        include_bytes!("../src/database/full_sqlite/tests.rs"),
    ),
    ("src/executor.rs", include_bytes!("../src/executor.rs")),
    (
        "src/executor/allocator.rs",
        include_bytes!("../src/executor/allocator.rs"),
    ),
    (
        "src/executor/host.rs",
        include_bytes!("../src/executor/host.rs"),
    ),
    (
        "src/executor/host/functions.rs",
        include_bytes!("../src/executor/host/functions.rs"),
    ),
    (
        "src/executor/host/runtime_version.rs",
        include_bytes!("../src/executor/host/runtime_version.rs"),
    ),
    (
        "src/executor/host/tests.rs",
        include_bytes!("../src/executor/host/tests.rs"),
    ),
    (
        "src/executor/host/tests/hash_algorithms.rs",
        include_bytes!("../src/executor/host/tests/hash_algorithms.rs"),
    ),
    (
        "src/executor/host/tests/initialization.rs",
        include_bytes!("../src/executor/host/tests/initialization.rs"),
    ),
    (
        "src/executor/host/tests/rococo-genesis.wasm",
        include_bytes!("../src/executor/host/tests/rococo-genesis.wasm"),
    ),
    (
        "src/executor/host/tests/run.rs",
        include_bytes!("../src/executor/host/tests/run.rs"),
    ),
    (
        "src/executor/host/westend-runtime-v9300.wasm",
        include_bytes!("../src/executor/host/westend-runtime-v9300.wasm"),
    ),
    (
        "src/executor/host/zstd.rs",
        include_bytes!("../src/executor/host/zstd.rs"),
    ),
    (
        "src/executor/host/zstd/example-runtime.wasm.zstd",
        include_bytes!("../src/executor/host/zstd/example-runtime.wasm.zstd"),
    ),
    (
        "src/executor/host/zstd/polkadot-runtime-v9160.wasm.zstd",
        include_bytes!("../src/executor/host/zstd/polkadot-runtime-v9160.wasm.zstd"),
    ),
    (
        "src/executor/host/zstd/tests.rs",
        include_bytes!("../src/executor/host/zstd/tests.rs"),
    ),
    (
        "src/executor/runtime_call.rs",
        include_bytes!("../src/executor/runtime_call.rs"),
    ),
    (
        "src/executor/runtime_call/child-trie-create-multiple.json",
        include_bytes!("../src/executor/runtime_call/child-trie-create-multiple.json"),
    ),
    (
        "src/executor/runtime_call/child-trie-create-one.json",
        include_bytes!("../src/executor/runtime_call/child-trie-create-one.json"),
    ),
    (
        "src/executor/runtime_call/child-trie-destroy.json",
        include_bytes!("../src/executor/runtime_call/child-trie-destroy.json"),
    ),
    (
        "src/executor/runtime_call/child-trie-read-basic.json",
        include_bytes!("../src/executor/runtime_call/child-trie-read-basic.json"),
    ),
    (
        "src/executor/runtime_call/tests.rs",
        include_bytes!("../src/executor/runtime_call/tests.rs"),
    ),
    (
        "src/executor/storage_diff.rs",
        include_bytes!("../src/executor/storage_diff.rs"),
    ),
    (
        "src/executor/trie_root_calculator.rs",
        include_bytes!("../src/executor/trie_root_calculator.rs"),
    ),
    (
        "src/executor/trie_root_calculator/tests.rs",
        include_bytes!("../src/executor/trie_root_calculator/tests.rs"),
    ),
    (
        "src/executor/vm.rs",
        include_bytes!("../src/executor/vm.rs"),
    ),
    (
        "src/executor/vm/interpreter.rs",
        include_bytes!("../src/executor/vm/interpreter.rs"),
    ),
    (
        "src/executor/vm/jit.rs",
        include_bytes!("../src/executor/vm/jit.rs"),
    ),
    (
        "src/executor/vm/test-polkadot-runtime-v9160.wasm",
        include_bytes!("../src/executor/vm/test-polkadot-runtime-v9160.wasm"),
    ),
    (
        "src/executor/vm/tests.rs",
        include_bytes!("../src/executor/vm/tests.rs"),
    ),
    (
        "src/identity/ss58.rs",
        include_bytes!("../src/identity/ss58.rs"),
    ),
    ("src/json_rpc.rs", include_bytes!("../src/json_rpc.rs")),
    (
        "src/json_rpc/methods.rs",
        include_bytes!("../src/json_rpc/methods.rs"),
    ),
    (
        "src/json_rpc/parse.rs",
        include_bytes!("../src/json_rpc/parse.rs"),
    ),
    (
        "src/json_rpc/payment_info.rs",
        include_bytes!("../src/json_rpc/payment_info.rs"),
    ),
    (
        "src/json_rpc/service.rs",
        include_bytes!("../src/json_rpc/service.rs"),
    ),
    (
        "src/json_rpc/service/client_main_task.rs",
        include_bytes!("../src/json_rpc/service/client_main_task.rs"),
    ),
    (
        "src/json_rpc/service/deliver_channel.rs",
        include_bytes!("../src/json_rpc/service/deliver_channel.rs"),
    ),
    ("src/trie.rs", include_bytes!("../src/trie.rs")),
    (
        "src/trie/branch_search.rs",
        include_bytes!("../src/trie/branch_search.rs"),
    ),
    (
        "src/trie/branch_search/tests.rs",
        include_bytes!("../src/trie/branch_search/tests.rs"),
    ),
    (
        "src/trie/calculate_root.rs",
        include_bytes!("../src/trie/calculate_root.rs"),
    ),
    (
        "src/trie/minimize_proof.rs",
        include_bytes!("../src/trie/minimize_proof.rs"),
    ),
    (
        "src/trie/nibble.rs",
        include_bytes!("../src/trie/nibble.rs"),
    ),
    (
        "src/trie/prefix_proof.rs",
        include_bytes!("../src/trie/prefix_proof.rs"),
    ),
    (
        "src/trie/prefix_proof/test.json",
        include_bytes!("../src/trie/prefix_proof/test.json"),
    ),
    (
        "src/trie/prefix_proof/tests.rs",
        include_bytes!("../src/trie/prefix_proof/tests.rs"),
    ),
    (
        "src/trie/proof_decode.rs",
        include_bytes!("../src/trie/proof_decode.rs"),
    ),
    (
        "src/trie/proof_decode/issue_2035_bis_proof",
        include_bytes!("../src/trie/proof_decode/issue_2035_bis_proof"),
    ),
    (
        "src/trie/proof_decode/issue_2035_proof",
        include_bytes!("../src/trie/proof_decode/issue_2035_proof"),
    ),
    (
        "src/trie/proof_decode/issue_2035_ter_proof",
        include_bytes!("../src/trie/proof_decode/issue_2035_ter_proof"),
    ),
    (
        "src/trie/proof_decode/tests.rs",
        include_bytes!("../src/trie/proof_decode/tests.rs"),
    ),
    (
        "src/trie/proof_encode.rs",
        include_bytes!("../src/trie/proof_encode.rs"),
    ),
    (
        "src/trie/trie_node.rs",
        include_bytes!("../src/trie/trie_node.rs"),
    ),
    (
        "src/trie/trie_structure.rs",
        include_bytes!("../src/trie/trie_structure.rs"),
    ),
    (
        "src/trie/trie_structure/tests.rs",
        include_bytes!("../src/trie/trie_structure/tests.rs"),
    ),
    ("src/util.rs", include_bytes!("../src/util.rs")),
    (
        "src/util/leb128.rs",
        include_bytes!("../src/util/leb128.rs"),
    ),
    (
        "src/util/protobuf.rs",
        include_bytes!("../src/util/protobuf.rs"),
    ),
];

#[test]
fn all_state_and_runtime_source_files_are_present_and_non_empty() {
    for (path, content) in REQUIRED_FILES {
        assert!(!content.is_empty(), "状态/runtime 来源文件为空: {path}");
    }
}
