# 本文件是现有构建器的安装后验收入口，不创建另一套 Core/Host 构建。
set(CMAKE_C_EXTENSIONS OFF)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CITIZENSDK_CONSUMER_PREFIX "" CACHE PATH "Exact current CitizenSDK installation prefix")
set(CITIZENSDK_CONSUMER_VERSION "" CACHE STRING "Exact installed CitizenSDK version")
set(CITIZENSDK_PLATFORM "" CACHE STRING "LinuxARM or LinuxAMD")
set(CITIZENSDK_TEST_WORK_DIR "" CACHE PATH "Existing exclusive mode-0700 consumer state root")

if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR CMAKE_CROSSCOMPILING)
  message(FATAL_ERROR "CitizenSDK consumers require native Linux execution")
endif()
if(NOT CITIZENSDK_PLATFORM STREQUAL "LinuxARM" AND
   NOT CITIZENSDK_PLATFORM STREQUAL "LinuxAMD")
  message(FATAL_ERROR "CITIZENSDK_PLATFORM must be LinuxARM or LinuxAMD")
endif()
if((CITIZENSDK_PLATFORM STREQUAL "LinuxARM" AND
    NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$") OR
   (CITIZENSDK_PLATFORM STREQUAL "LinuxAMD" AND
    NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$"))
  message(FATAL_ERROR "CitizenSDK consumer architecture differs from the installation")
endif()
if(NOT CITIZENSDK_CONSUMER_VERSION MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
  message(FATAL_ERROR "CITIZENSDK_CONSUMER_VERSION must be the exact SDK version")
endif()
foreach(_path CITIZENSDK_CONSUMER_PREFIX CITIZENSDK_TEST_WORK_DIR)
  if(NOT IS_ABSOLUTE "${${_path}}" OR NOT IS_DIRECTORY "${${_path}}" OR
     "${${_path}}" STREQUAL "/")
    message(FATAL_ERROR "${_path} must be an existing absolute non-root directory")
  endif()
  get_filename_component(_real "${${_path}}" REALPATH)
  if(NOT "${_real}" STREQUAL "${${_path}}")
    message(FATAL_ERROR "${_path} must not contain links or noncanonical components")
  endif()
endforeach()
get_filename_component(_sdk_source "${CMAKE_CURRENT_LIST_DIR}/../.." REALPATH)
get_filename_component(_consumer_build "${CMAKE_BINARY_DIR}" REALPATH)
cmake_path(IS_PREFIX _sdk_source "${_consumer_build}" NORMALIZE _build_in_source)
cmake_path(IS_PREFIX _sdk_source "${CITIZENSDK_TEST_WORK_DIR}" NORMALIZE _state_in_source)
cmake_path(IS_PREFIX _sdk_source "${CITIZENSDK_CONSUMER_PREFIX}" NORMALIZE _install_in_source)
if(_build_in_source OR _state_in_source OR _install_in_source)
  message(FATAL_ERROR "CitizenSDK consumer artifacts and state must stay outside SDK sources")
endif()

# 不搜索系统包、环境前缀或源码 target；EXACT 拒绝同名但不同版本的包配置。
set(_package_dir "${CITIZENSDK_CONSUMER_PREFIX}/lib/${CITIZENSDK_PLATFORM}/cmake/CitizenSDK")
set(CitizenSDK_DIR "${_package_dir}")
find_package(CitizenSDK ${CITIZENSDK_CONSUMER_VERSION} EXACT CONFIG REQUIRED
  PATHS "${_package_dir}" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
foreach(_kind Core Host)
  if(NOT TARGET CitizenSDK::${_kind})
    message(FATAL_ERROR "CitizenSDK installation is missing ${_kind}")
  endif()
  get_target_property(_imported CitizenSDK::${_kind} IMPORTED)
  if(NOT _imported)
    message(FATAL_ERROR "CitizenSDK consumer must link imported Core/Host")
  endif()
  if(_kind STREQUAL "Core")
    set(_library libcitizensdk.so)
  else()
    set(_library libcitizensdk_host.so)
  endif()
  set(_expected "${CITIZENSDK_CONSUMER_PREFIX}/lib/${CITIZENSDK_PLATFORM}/${_library}")
  if(NOT EXISTS "${_expected}" OR IS_DIRECTORY "${_expected}" OR IS_SYMLINK "${_expected}")
    message(FATAL_ERROR "CitizenSDK consumer requires the ordinary installed ${_library}")
  endif()
  get_target_property(_configs CitizenSDK::${_kind} IMPORTED_CONFIGURATIONS)
  set(_locations)
  get_target_property(_location CitizenSDK::${_kind} IMPORTED_LOCATION)
  if(_location)
    list(APPEND _locations "${_location}")
  endif()
  foreach(_config IN LISTS _configs)
    string(TOUPPER "${_config}" _upper)
    get_target_property(_location CitizenSDK::${_kind} IMPORTED_LOCATION_${_upper})
    if(_location)
      list(APPEND _locations "${_location}")
    endif()
  endforeach()
  if(NOT _locations)
    message(FATAL_ERROR "CitizenSDK imported ${_kind} has no runtime location")
  endif()
  foreach(_location IN LISTS _locations)
    if(NOT _location STREQUAL _expected)
      message(FATAL_ERROR "CitizenSDK consumer resolved a different runtime installation")
    endif()
  endforeach()
  get_target_property(_includes CitizenSDK::${_kind} INTERFACE_INCLUDE_DIRECTORIES)
  if(NOT _includes)
    message(FATAL_ERROR "CitizenSDK imported ${_kind} has no public headers")
  endif()
  foreach(_include IN LISTS _includes)
    if(NOT _include STREQUAL "${CITIZENSDK_CONSUMER_PREFIX}/include")
      message(FATAL_ERROR "CitizenSDK consumer must not include source/private headers")
    endif()
  endforeach()
endforeach()
if(NOT CITIZENSDK_ASSET_DIR STREQUAL
   "${CITIZENSDK_CONSUMER_PREFIX}/share/citizensdk/chain")
  message(FATAL_ERROR "CitizenSDK consumer must use the installed chain assets")
endif()
foreach(_asset manifest.json chainspec.json light_sync_state.json)
  if(NOT EXISTS "${CITIZENSDK_ASSET_DIR}/${_asset}" OR
     IS_DIRECTORY "${CITIZENSDK_ASSET_DIR}/${_asset}" OR
     IS_SYMLINK "${CITIZENSDK_ASSET_DIR}/${_asset}")
    message(FATAL_ERROR "CitizenSDK installed chain asset is missing or unsafe")
  endif()
endforeach()

find_package(Threads REQUIRED)
enable_testing()
add_executable(citizen_sdk_c_consumer citizen_sdk_c_consumer.c)
target_compile_features(citizen_sdk_c_consumer PRIVATE c_std_11)
target_compile_definitions(citizen_sdk_c_consumer PRIVATE _POSIX_C_SOURCE=200809L)
add_executable(citizen_sdk_cpp_consumer citizen_sdk_cpp_consumer.cc)
target_compile_features(citizen_sdk_cpp_consumer PRIVATE cxx_std_17)
foreach(_consumer citizen_sdk_c_consumer citizen_sdk_cpp_consumer)
  target_link_libraries(${_consumer} PRIVATE CitizenSDK::Host Threads::Threads)
  target_compile_options(${_consumer} PRIVATE
    -UNDEBUG -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -Werror)
  # 测试可执行文件直接定位本轮安装双库，不依赖 LD_LIBRARY_PATH 或源码树。
  set_target_properties(${_consumer} PROPERTIES
    BUILD_RPATH "${CITIZENSDK_CONSUMER_PREFIX}/lib/${CITIZENSDK_PLATFORM}")
endforeach()
add_test(NAME CitizenSDK.Linux.CConsumer COMMAND citizen_sdk_c_consumer
  "${CITIZENSDK_TEST_WORK_DIR}" "${CITIZENSDK_ASSET_DIR}")
add_test(NAME CitizenSDK.Linux.CppConsumer COMMAND citizen_sdk_cpp_consumer
  "${CITIZENSDK_TEST_WORK_DIR}" "${CITIZENSDK_ASSET_DIR}")
set_tests_properties(CitizenSDK.Linux.CConsumer CitizenSDK.Linux.CppConsumer
  PROPERTIES TIMEOUT 180 RUN_SERIAL TRUE LABELS "CitizenSDK;LinuxConsumer")
